apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: orjoeslo/k8s-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # value: '10.43.170.29'
              value: auth-service.default
