version: "3"
services:
  auth:
    build: ./auth-api
    ports:
      - '8000:3000'
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
  users:
    build: ./users-api
    ports:
      - '8080:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://orlando:0uPLsih3RLhvhbsG@cluster0.or9h8.mongodb.net/users?retryWrites=true&w=majority&appName=Cluster0'
      AUTH_API_ADDRESS: 'auth:3000'
  tasks:
    build: ./tasks-api
    ports:
      - '3000:3000'
    environment:
      MONGODB_CONNECTION_URI: 'mongodb+srv://orlando:0uPLsih3RLhvhbsG@cluster0.or9h8.mongodb.net/tasks?retryWrites=true&w=majority&appName=Cluster0'
      AUTH_API_ADDRESS: 'auth:3000'