apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # This name comes from the standard storageClass "kubectl get sc"
  resources: # This is the equivalent to Capacity in the PV configuration. Defines the resources to be claimed. In this case storage.
    requests:
      storage: 1Gi
